"""followers

Revision ID: 47db6c7f00da
Revises: 16cdfd88661a
Create Date: 2023-04-11 17:30:15.344434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47db6c7f00da'
down_revision = '16cdfd88661a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
